import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed bg-[url('/img/tahm_kench/TahmKench_30.jpg')] bg-center bg-cover w-full h-full blur-sm saturate-150 scale-[1.2] -scale-x-[1.2]  opacity-20 -z-40" />
        <header>
          <nav className="flex">
            <a href="/">
              <div className="flex h-16 w-16 p-2 m-4 justify-center items-center">
                <img src="/img/tahm_kench/icon.png" alt="logo" />
              </div>
            </a>
            <ul className="flex gap-x-6 text-gray-300 items-center">
              <li className=" hover:text-gray-100 hover:border-b border-b-gray-100">
                <a href="/team_builder">Team Builder</a>
              </li>
              <li className=" hover:text-gray-100 hover:border-b border-b-gray-100">
                <a href="/team_builder">Multisearch</a>
              </li>
              <li className=" hover:text-gray-100 hover:border-b border-b-gray-100">
                <a href="/team_builder">Communities</a>
              </li>
              <li className=" hover:text-gray-100 hover:border-b border-b-gray-100">
                <a href="/team_builder">FAQ</a>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
